/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./tests/unit_tests/main.check" instead.
 */

#include <check.h>

#include "../../s21_matrix.h"
void s21_init_matrix(double number, matrix_t *A) {
  for (int x = 0; x < A->rows; x += 1) {
    for (int y = 0; y < A->columns; number += 1.0, y += 1)
      A->matrix[x][y] = number;
  }
}
START_TEST(s21_calc_complements_test_1)
{
int rows = 2;
int columns = 2;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
A.matrix[0][0] = 5;
A.matrix[0][1] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 7;
C.matrix[0][0] = 7;
C.matrix[0][1] = -4;
C.matrix[1][0] = -1;
C.matrix[1][1] = 5;
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(0, ret);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_calc_complements_test_2)
{
int rows = 3;
int columns = 3;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
A.matrix[0][0] = 6;
A.matrix[0][1] = 1;
A.matrix[0][2] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 1;
A.matrix[1][2] = 2;
A.matrix[2][0] = 3;
A.matrix[2][1] = 2;
A.matrix[2][2] = 4;

C.matrix[0][0] = 0;
C.matrix[0][1] = -10;
C.matrix[0][2] = 5;
C.matrix[1][0] = -2;
C.matrix[1][1] = 21;
C.matrix[1][2] = -9;
C.matrix[2][0] = 1;
C.matrix[2][1] = -8;
C.matrix[2][2] = 2;
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(0, ret);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_calc_complements_test_3)
{
int rows = rand() % 10 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, rows, &A);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < rows; j++) {
    double t = rand();
    A.matrix[i][j] = t / 7;
  }
}
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(0, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&R);

}
END_TEST

START_TEST(s21_calc_complements_test_4)
{
int rows = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, rows + 1, &A);
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(0, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_calc_complements_test_5)
{
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_calc_complements_test_6)
{
double m[3][3] = {{1, 2, 3}, {0, 4, 2}, {5, 2, 1}};
double r[3][3] = {{0, 10, -20}, {4, -14, 8}, {-8, -2, 4}};
matrix_t matrix, res_org, res_my;
s21_create_matrix(3, 3, &matrix);
s21_create_matrix(3, 3, &res_org);
for (int i = 0; i < matrix.rows; i++) {
  for (int j = 0; j < matrix.columns; j++) {
    matrix.matrix[i][j] = m[i][j];
  }
}
for (int i = 0; i < matrix.rows; i++) {
  for (int j = 0; j < matrix.columns; j++) {
    res_org.matrix[i][j] = r[i][j];
  }
}
int ret = s21_calc_complements(&matrix, &res_my);
ck_assert_int_eq(ret, 0);
ret = s21_eq_matrix(&res_org, &res_my);
ck_assert_int_eq(ret, 1);
s21_remove_matrix(&matrix);
s21_remove_matrix(&res_my);

}
END_TEST

START_TEST(s21_calc_complements_test_7)
{
matrix_t R = {0};
int ret = s21_calc_complements(NULL, &R);
ck_assert_int_eq(1, ret);

}
END_TEST

START_TEST(s21_calc_complements_test_8)
{
matrix_t R = {0};
matrix_t A = {0};
s21_create_matrix(1, 1, &A);
int ret = s21_calc_complements(&A, &R);
ck_assert_int_eq(2, ret);
}
END_TEST

START_TEST(s21_create_matrix_test_1)
{
matrix_t A;
int res = s21_create_matrix(2, 2, &A);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(s21_create_matrix_test_2)
{
matrix_t A;
int res = s21_create_matrix(0, 2, &A);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(s21_create_matrix_test_3)
{
int res = s21_create_matrix(3, 3, NULL);
ck_assert_int_eq(res, 1);
}
END_TEST

START_TEST(s21_determinant_matrix_test_1)
{
int rows = 1;
int columns = 1;
matrix_t A = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 5;
double det = 5;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_eq(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_2)
{
int rows = 2;
int columns = 2;
matrix_t A = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 5;
A.matrix[0][1] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 7;
double det = 31;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_eq(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_3)
{
int rows = 3;
int columns = 3;
matrix_t A = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 1;
A.matrix[0][1] = 2;
A.matrix[0][2] = 3;
A.matrix[1][0] = 4;
A.matrix[1][1] = 5;
A.matrix[1][2] = 6;
A.matrix[2][0] = 7;
A.matrix[2][1] = 8;
A.matrix[2][2] = 9;
double det = 0;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_eq(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_4)
{
int rows = 3;
int columns = 3;
matrix_t A = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 5;
A.matrix[0][1] = 1;
A.matrix[0][2] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 7;
A.matrix[1][2] = 5;
A.matrix[2][0] = 3;
A.matrix[2][1] = 3;
A.matrix[2][2] = 4;
double det = 55;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_eq(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_5)
{
int rows = 3;
int columns = 3;
matrix_t A = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 5;
A.matrix[0][1] = 1;
A.matrix[0][2] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 7;
A.matrix[1][2] = 5;
A.matrix[2][0] = 3;
A.matrix[2][1] = 3;
A.matrix[2][2] = 4;
double det = 55;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_eq(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_6)
{
int rows = rand() % 10 + 1;
matrix_t A = {0};
s21_create_matrix(rows, rows, &A);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < rows; j++) {
    A.matrix[i][j] = 4;
  }
}
double det = 5;
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(0, ret);
ck_assert_double_ne(res, det);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_determinant_matrix_test_7)
{
int rows = rand() % 100 + 1;
matrix_t A = {0};
s21_create_matrix(rows, 0, &A);
double res = 0;
int ret = s21_determinant(&A, &res);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_eq_matrix_test_1)
{
matrix_t A;
matrix_t B;
s21_create_matrix(3, 3, &A);
s21_create_matrix(3, 3, &B);
s21_init_matrix(1, &A);
s21_init_matrix(1, &B);
int res = s21_eq_matrix(&A, &B);
ck_assert_int_eq(res, 1);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_eq_matrix_test_2)
{
matrix_t A;
matrix_t B;
s21_create_matrix(3, 3, &A);
s21_create_matrix(3, 3, &B);
s21_init_matrix(2, &A);
s21_init_matrix(1, &B);
int res = s21_eq_matrix(&A, &B);
ck_assert_int_eq(res, 0);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_eq_matrix_test_3)
{
matrix_t A;
matrix_t B;
s21_create_matrix(2, 3, &A);
s21_create_matrix(3, 3, &B);
s21_init_matrix(1, &A);
s21_init_matrix(1, &B);
int res = s21_eq_matrix(&A, &B);
ck_assert_int_eq(res, 0);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_eq_matrix_test_4)
{
matrix_t A;
s21_create_matrix(2, 3, &A);
s21_init_matrix(1, &A);
int res = s21_eq_matrix(&A, NULL);
ck_assert_int_eq(res, 0);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_eq_matrix_test_5)
{
matrix_t B;
s21_create_matrix(3, 3, &B);
s21_init_matrix(1, &B);
int res = s21_eq_matrix(NULL, &B);
ck_assert_int_eq(res, 0);
s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_inverse_matrix_simple1)
{
int rows = 1;
int columns = 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
A.matrix[0][0] = 5;
int ret = s21_inverse_matrix(&A, &R);
double inv = 0.2;
ck_assert_int_eq(0, ret);
ck_assert_double_eq(inv, R.matrix[0][0]);
s21_remove_matrix(&A);
s21_remove_matrix(&R);

}
END_TEST

START_TEST(s21_inverse_matrix_simple_2x1)
{
int rows = 2;
int columns = 2;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
A.matrix[0][0] = 3;
A.matrix[0][1] = 2;
A.matrix[1][0] = 4;
A.matrix[1][1] = 1;

C.matrix[0][0] = -0.2;
C.matrix[0][1] = 0.4;
C.matrix[1][0] = 0.8;
C.matrix[1][1] = -0.6;
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(0, ret);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_inverse_matrix_simple_3x1)
{
int rows = 3;
int columns = 3;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
A.matrix[0][0] = 6;
A.matrix[0][1] = 1;
A.matrix[0][2] = 1;
A.matrix[1][0] = 4;
A.matrix[1][1] = 1;
A.matrix[1][2] = 2;
A.matrix[2][0] = 3;
A.matrix[2][1] = 2;
A.matrix[2][2] = 4;
C.matrix[0][0] = 0;
C.matrix[0][1] = 0.4;
C.matrix[0][2] = -0.2;
C.matrix[1][0] = 2;
C.matrix[1][1] = -4.2;
C.matrix[1][2] = 1.6;
C.matrix[2][0] = -1;
C.matrix[2][1] = 1.8;
C.matrix[2][2] = -0.4;
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(0, ret);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_inverse_matrix_det_1)
{
int rows = 2;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, rows, &A);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < rows; j++) {
    A.matrix[i][j] = 7;
  }
}
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_inverse_matrix_wrong_2x1)
{
int rows = 2;
int columns = 2;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
A.matrix[0][0] = 3;
A.matrix[0][1] = 2;
A.matrix[1][0] = 4;
A.matrix[1][1] = 1;
C.matrix[0][0] = 0;
C.matrix[0][1] = 0;
C.matrix[1][0] = 0.8;
C.matrix[1][1] = -0.6;
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(0, ret);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_inverse_matrix_wrong_rc1)
{
int rows = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, rows + 1, &A);
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_inverse_matrix_null1)
{
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
int ret = s21_inverse_matrix(&A, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_inverse_matrix1)
{
double m[3][3] = {{2, 5, 7}, {6, 3, 4}, {5, -2, -3}};
double r[3][3] = {{1, -1, 1}, {-38, 41, -34}, {27, -29, 24}};
matrix_t matrix, res_org, res_my;
s21_create_matrix(3, 3, &matrix);
s21_create_matrix(3, 3, &res_org);
for (int i = 0; i < matrix.rows; i++) {
  for (int j = 0; j < matrix.columns; j++) {
    matrix.matrix[i][j] = m[i][j];
  }
}
for (int i = 0; i < matrix.rows; i++) {
  for (int j = 0; j < matrix.columns; j++) {
    res_org.matrix[i][j] = r[i][j];
  }
}
int ret = s21_inverse_matrix(&matrix, &res_my);
ck_assert_int_eq(ret, 0);
ret = s21_eq_matrix(&res_org, &res_my);
ck_assert_int_eq(ret, 1);
s21_remove_matrix(&matrix);
s21_remove_matrix(&res_my);
s21_remove_matrix(&res_org);
}
END_TEST

START_TEST(s21_mult_matrix_test_1)
{
int rowsA = 2;
int columnsA = 1;
int columnsB = 2;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rowsA, columnsA, &A);
s21_create_matrix(columnsA, columnsB, &B);
s21_create_matrix(rowsA, columnsB, &C);
for (int i = 0; i < rowsA; i++) {
  for (int j = 0; j < columnsA; j++) {
    A.matrix[i][j] = i + 2;
  }
}
for (int i = 0; i < columnsA; i++) {
  for (int j = 0; j < columnsB; j++) {
    B.matrix[i][j] = j + 1;
  }
}
C.matrix[0][0] = 2;
C.matrix[0][1] = 4;
C.matrix[1][0] = 3;
C.matrix[1][1] = 6;
int ret = s21_mult_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_mult_matrix_test_2)
{
int rowsA = rand() % 100 + 1;
int columnsA = rand() % 100 + 1;
int columnsB = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rowsA, columnsA, &A);
s21_create_matrix(columnsA, columnsB, &B);
s21_create_matrix(rowsA, columnsB, &C);
for (int i = 0; i < rowsA; i++) {
  for (int j = 0; j < columnsA; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
  }
}
for (int i = 0; i < columnsA; i++) {
  for (int j = 0; j < columnsB; j++) {
    double t = rand();
    B.matrix[i][j] = t / 5;
  }
}
for (int i = 0; i < C.rows; i++) {
  for (int j = 0; j < C.columns; j++) {
    for (int k = 0; k < A.columns; k++) {
      C.matrix[i][j] += A.matrix[i][k] * B.matrix[k][j];
    }
  }
}
int ret = s21_mult_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_mult_matrix_test_3)
{
int rowsA = rand() % 100 + 1;
int columnsA = rand() % 100 + 1;
int columnsB = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rowsA, columnsA, &A);
s21_create_matrix(columnsA, columnsB, &B);
s21_create_matrix(rowsA, columnsB, &C);
for (int i = 0; i < rowsA; i++) {
  for (int j = 0; j < columnsA; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
  }
}
for (int i = 0; i < columnsA; i++) {
  for (int j = 0; j < columnsB; j++) {
    double t = rand();
    B.matrix[i][j] = t / 5;
  }
}
int temp = 0;
for (int i = 0; i < C.rows; i++) {
  for (int j = 0; j < C.columns; j++) {
    for (int k = 0; k < A.columns; k++) {
      temp = A.matrix[i][k] * B.matrix[k][j] + 10;
      C.matrix[i][j] += temp;
    }
  }
}
int ret = s21_mult_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_mult_matrix_test_4)
{
int rowsA = rand() % 100 + 1;
int columnsA = rand() % 100 + 1;
int columnsB = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rowsA, columnsA, &A);
s21_create_matrix(columnsA + 1, columnsB, &B);
int ret = s21_mult_matrix(&A, &B, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_mult_matrix_test_5)
{
int rowsA = 0;
int columnsA = rand() % 100 + 1;
int columnsB = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rowsA, columnsA, &A);
s21_create_matrix(columnsA, columnsB, &B);
int ret = s21_mult_matrix(&A, &B, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_number1)
{
double number = (rand() % 100 + 1) / 3;
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 2;
    C.matrix[i][j] = number * A.matrix[i][j];
  }
}
int ret = s21_mult_number(&A, number, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_mult_number2)
{
double number = (rand() % 100 + 1) / 3;
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 2;
    C.matrix[i][j] = number * A.matrix[i][j] * 2;
  }
}
int ret = s21_mult_number(&A, number, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_mult_number3)
{
double number = (rand() % 100 + 1) / 3;
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
int ret = s21_mult_number(&A, number, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_remove_matrix_test_1)
{
matrix_t A;
s21_create_matrix(3, 3, &A);
s21_init_matrix(1, &A);
s21_remove_matrix(&A);
ck_assert_ptr_null(A.matrix);

}
END_TEST

START_TEST(s21_remove_matrix_test_2)
{
s21_remove_matrix(NULL);

}
END_TEST

START_TEST(s21_remove_matrix_test_3)
{
s21_remove_matrix(0);
}
END_TEST

START_TEST(s21_sub_matrix_test_1)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
    B.matrix[i][j] = t / 5;
    C.matrix[i][j] = A.matrix[i][j] - B.matrix[i][j];
  }
}
int ret = s21_sub_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_sub_matrix_test_2)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
    B.matrix[i][j] = t / 5;
    C.matrix[i][j] = A.matrix[i][j] - B.matrix[i][j] + 1;
  }
}
int ret = s21_sub_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_sub_matrix_test_3)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows + 1, columns, &B);
int ret = s21_sub_matrix(&A, &B, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_sub_matrix_test_4)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns + 1, &A);
s21_create_matrix(rows, columns, &B);
int ret = s21_sub_matrix(&A, &B, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_sub_matrix_test_5)
{
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
int ret = s21_sub_matrix(&A, &B, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sum_matrix_test_1)
{

int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
    B.matrix[i][j] = t / 5;
    C.matrix[i][j] = A.matrix[i][j] + B.matrix[i][j];
  }
}
int ret = s21_sum_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_sum_matrix_test_2)
{
int res = 0;
matrix_t A = {0};
matrix_t B = {0};
matrix_t Z = {0};
matrix_t X = {0};

s21_create_matrix(4, 4, &A);
s21_init_matrix(1.0, &A);

s21_create_matrix(4, 4, &B);
s21_init_matrix(1.0, &B);

s21_sum_matrix(&A, &B, &Z);

s21_create_matrix(4, 4, &X);
X.matrix[0][0] = 2.0;
X.matrix[0][1] = 4.0;
X.matrix[0][2] = 6.0;
X.matrix[0][3] = 8.0;
X.matrix[1][0] = 10.0;
X.matrix[1][1] = 12.0;
X.matrix[1][2] = 14.0;
X.matrix[1][3] = 16.0;
X.matrix[2][0] = 18.0;
X.matrix[2][1] = 20.0;
X.matrix[2][2] = 22.0;
X.matrix[2][3] = 24.0;
X.matrix[3][0] = 26.0;
X.matrix[3][1] = 28.0;
X.matrix[3][2] = 30.0;
X.matrix[3][3] = 32.0;

res = s21_eq_matrix(&X, &Z);

s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&X);
s21_remove_matrix(&Z);

ck_assert_int_eq(res, SUCCESS);

}
END_TEST

START_TEST(s21_sum_matrix_test_3)
{
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
int ret = s21_sum_matrix(&A, &B, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_sum_matrix_test_4)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows, columns, &B);
s21_create_matrix(rows, columns, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 3;
    B.matrix[i][j] = t / 5;
    C.matrix[i][j] = A.matrix[i][j] + B.matrix[i][j] + 1;
  }
}
int ret = s21_sum_matrix(&A, &B, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_sum_matrix_test_5)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(rows + 1, columns, &B);
int ret = s21_sum_matrix(&A, &B, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);

}
END_TEST

START_TEST(s21_sum_matrix_test_6)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t B = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns + 1, &A);
s21_create_matrix(rows, columns, &B);
int ret = s21_sum_matrix(&A, &B, &R);
ck_assert_int_eq(2, ret);
s21_remove_matrix(&A);
s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_transpose_matrix_test_1)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(columns, rows, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 7;
    C.matrix[j][i] = t / 7;
  }
}
int ret = s21_transpose(&A, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(SUCCESS, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_transpose_matrix_test_2)
{
int rows = rand() % 100 + 1;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
matrix_t C = {0};
s21_create_matrix(rows, columns, &A);
s21_create_matrix(columns, rows, &C);
for (int i = 0; i < rows; i++) {
  for (int j = 0; j < columns; j++) {
    double t = rand();
    A.matrix[i][j] = t / 7;
    C.matrix[j][i] = t / 7 + 1;
  }
}
int ret = s21_transpose(&A, &R);
int res = s21_eq_matrix(&C, &R);
ck_assert_int_eq(0, ret);
ck_assert_int_eq(FAILURE, res);
s21_remove_matrix(&A);
s21_remove_matrix(&R);
s21_remove_matrix(&C);

}
END_TEST

START_TEST(s21_transpose_matrix_test_3)
{
int rows = 0;
int columns = rand() % 100 + 1;
matrix_t A = {0};
matrix_t R = {0};
s21_create_matrix(rows, columns, &A);
int ret = s21_transpose(&A, &R);
ck_assert_int_eq(1, ret);
s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_transpose_matrix_test_4)
{
matrix_t mat_1, res_mat, res_org;

s21_create_matrix(2, 2, &mat_1);
s21_create_matrix(2, 2, &res_org);
mat_1.matrix[0][0] = 1;
mat_1.matrix[0][1] = 2;
mat_1.matrix[1][0] = 3;
mat_1.matrix[1][1] = 4;
res_org.matrix[0][0] = 1;
res_org.matrix[0][1] = 3;
res_org.matrix[1][0] = 2;
res_org.matrix[1][1] = 4;
int ret = s21_transpose(&mat_1, &res_mat);
ck_assert_int_eq(ret, 0);
ret = s21_eq_matrix(&res_mat, &res_org);
ck_assert_int_eq(ret, 1);
s21_remove_matrix(&mat_1);
s21_remove_matrix(&res_mat);
s21_remove_matrix(&res_org);

double matrix[2][2] = {
    {1, 2},
    {3, 4},
};
double res[2][2] = {{1, 3}, {2, 4}};
s21_create_matrix(2, 2, &mat_1);
s21_create_matrix(2, 2, &res_org);
for (int i = 0; i < 2; i++) {
  for (int j = 0; j < 2; j++) {
    mat_1.matrix[i][j] = matrix[i][j];
  }
}
for (int i = 0; i < 2; i++) {
  for (int j = 0; j < 2; j++) {
    res_org.matrix[i][j] = res[i][j];
  }
}
ret = s21_transpose(&mat_1, &res_mat);
ck_assert_int_eq(ret, 0);
ret = s21_eq_matrix(&res_mat, &res_org);
ck_assert_int_eq(ret, 1);
s21_remove_matrix(&mat_1);
s21_remove_matrix(&res_mat);
s21_remove_matrix(&res_org);

}
END_TEST

START_TEST(s21_transpose_matrix_test_5)
{
int ret = s21_transpose(NULL, NULL);
ck_assert_int_eq(1, ret);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_calc_complements_test_1);
    tcase_add_test(tc1_1, s21_calc_complements_test_2);
    tcase_add_test(tc1_1, s21_calc_complements_test_3);
    tcase_add_test(tc1_1, s21_calc_complements_test_4);
    tcase_add_test(tc1_1, s21_calc_complements_test_5);
    tcase_add_test(tc1_1, s21_calc_complements_test_6);
    tcase_add_test(tc1_1, s21_calc_complements_test_7);
    tcase_add_test(tc1_1, s21_calc_complements_test_8);
    tcase_add_test(tc1_1, s21_create_matrix_test_1);
    tcase_add_test(tc1_1, s21_create_matrix_test_2);
    tcase_add_test(tc1_1, s21_create_matrix_test_3);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_1);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_2);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_3);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_4);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_5);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_6);
    tcase_add_test(tc1_1, s21_determinant_matrix_test_7);
    tcase_add_test(tc1_1, s21_eq_matrix_test_1);
    tcase_add_test(tc1_1, s21_eq_matrix_test_2);
    tcase_add_test(tc1_1, s21_eq_matrix_test_3);
    tcase_add_test(tc1_1, s21_eq_matrix_test_4);
    tcase_add_test(tc1_1, s21_eq_matrix_test_5);
    tcase_add_test(tc1_1, s21_inverse_matrix_simple1);
    tcase_add_test(tc1_1, s21_inverse_matrix_simple_2x1);
    tcase_add_test(tc1_1, s21_inverse_matrix_simple_3x1);
    tcase_add_test(tc1_1, s21_inverse_matrix_det_1);
    tcase_add_test(tc1_1, s21_inverse_matrix_wrong_2x1);
    tcase_add_test(tc1_1, s21_inverse_matrix_wrong_rc1);
    tcase_add_test(tc1_1, s21_inverse_matrix_null1);
    tcase_add_test(tc1_1, s21_inverse_matrix1);
    tcase_add_test(tc1_1, s21_mult_matrix_test_1);
    tcase_add_test(tc1_1, s21_mult_matrix_test_2);
    tcase_add_test(tc1_1, s21_mult_matrix_test_3);
    tcase_add_test(tc1_1, s21_mult_matrix_test_4);
    tcase_add_test(tc1_1, s21_mult_matrix_test_5);
    tcase_add_test(tc1_1, s21_mult_number1);
    tcase_add_test(tc1_1, s21_mult_number2);
    tcase_add_test(tc1_1, s21_mult_number3);
    tcase_add_test(tc1_1, s21_remove_matrix_test_1);
    tcase_add_test(tc1_1, s21_remove_matrix_test_2);
    tcase_add_test(tc1_1, s21_remove_matrix_test_3);
    tcase_add_test(tc1_1, s21_sub_matrix_test_1);
    tcase_add_test(tc1_1, s21_sub_matrix_test_2);
    tcase_add_test(tc1_1, s21_sub_matrix_test_3);
    tcase_add_test(tc1_1, s21_sub_matrix_test_4);
    tcase_add_test(tc1_1, s21_sub_matrix_test_5);
    tcase_add_test(tc1_1, s21_sum_matrix_test_1);
    tcase_add_test(tc1_1, s21_sum_matrix_test_2);
    tcase_add_test(tc1_1, s21_sum_matrix_test_3);
    tcase_add_test(tc1_1, s21_sum_matrix_test_4);
    tcase_add_test(tc1_1, s21_sum_matrix_test_5);
    tcase_add_test(tc1_1, s21_sum_matrix_test_6);
    tcase_add_test(tc1_1, s21_transpose_matrix_test_1);
    tcase_add_test(tc1_1, s21_transpose_matrix_test_2);
    tcase_add_test(tc1_1, s21_transpose_matrix_test_3);
    tcase_add_test(tc1_1, s21_transpose_matrix_test_4);
    tcase_add_test(tc1_1, s21_transpose_matrix_test_5);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
