/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./tests/unit_tests/main.check" instead.
 */

#include <check.h>

#include "../../s21_matrix.h"
void s21_init_matrix(double number, matrix_t *A) {
  for (int x = 0; x < A->rows; x += 1) {
    for (int y = 0; y < A->columns; number += 1.0, y += 1)
      A->matrix[x][y] = number;
  }
}
START_TEST(s21_create_matrix_test_1)
{
matrix_t A;
int res = s21_create_matrix(2, 2, &A);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(s21_create_matrix_test_2)
{
matrix_t A;
int res = s21_create_matrix(0, 2, &A);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(s21_create_matrix_test_3)
{
int res = s21_create_matrix(3, 3, NULL);
ck_assert_int_eq(res, 1);
}
END_TEST

START_TEST(s21_remove_matrix_test_1)
{
matrix_t A;
s21_create_matrix(3, 3, &A);
s21_init_matrix(1, &A);
s21_remove_matrix(&A);
ck_assert_ptr_null(A.matrix);

}
END_TEST

START_TEST(s21_remove_matrix_test_2)
{
s21_remove_matrix(NULL);

}
END_TEST

START_TEST(s21_remove_matrix_test_3)
{
s21_remove_matrix(0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_create_matrix_test_1);
    tcase_add_test(tc1_1, s21_create_matrix_test_2);
    tcase_add_test(tc1_1, s21_create_matrix_test_3);
    tcase_add_test(tc1_1, s21_remove_matrix_test_1);
    tcase_add_test(tc1_1, s21_remove_matrix_test_2);
    tcase_add_test(tc1_1, s21_remove_matrix_test_3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
